spring:
  application:
    name: Mgr

  datasource:
    url: jdbc:mysql://localhost:3306/hr_mgr?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    host: localhost
    port: 6379

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: group-ab
#      enable-auto-commit: false
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"

  kafka-var:
    server: localhost:9092
    group-id:
      attendance: attendance-group
    consumer:
      auto-offset-reset: latest
    topic:
      attendance: attendance-topic


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

app:
  giant_data_init: none

server:
  connection-timeout: 120s  # 클라이언트 요청 수락을 기다리는 최대 시간
  tomcat:
    max-threads: 500
    accept-count: 10000
    max-connections: 12000

    connection-timeout: 60s # Keep-Alive 연결 유지 시간 증가
#    accesslog:
#      enabled: true
#      pattern: "%h %l %u %t %r %s %b"
#    basedir: logs
