spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hr_mgr?useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server-name: master