spring:

  jpa:
    properties:
      hibernate:
        show_sql: false

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server-name: master
attendance-threads: 2
attendance-calculate-threads: 4