spring:
  application:
    name: Mgr

  datasource:
    url: jdbc:mysql://localhost:3306/hr_mgr?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
